#!/bin/ksh
 
# Template script for running Cadence Xcelium simulator (XMCSIM) on Cadence Modus DFT Software Solution generated test vectors.
 
#  Generated by Genus(TM) Synthesis Solution 20.11-s111_1
 
export WORKDIR=./test_scripts
 
xrun \
   +access+rwc \
   +xmstatus \
   +xm64bit \
   +TESTFILE1=$WORKDIR/testresults/verilog/VER.FULLSCAN.counter_atpg.data.scan.ex1.ts1.verilog \
   +TESTFILE2=$WORKDIR/testresults/verilog/VER.FULLSCAN.counter_atpg.data.logic.ex1.ts2.verilog \
   +HEARTBEAT \
   +FAILSET \
   +xmtimescale+1ns/1ps \
   +xmoverride_timescale \
   +xmseq_udp_delay+2ps \
   +libext+.v+.V+.z+.Z+.gz \
   +xmlibdirname+$WORKDIR/Inca_libs_16_42_53 \
   -l $WORKDIR/ncverilog_FULLSCAN.log \
  -v slow.v \
$WORKDIR/counter.test_netlist.v \
$WORKDIR/testresults/verilog/VER.FULLSCAN.counter_atpg.mainsim.v

