
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Feb 17 2025 16:42:53 IST (Feb 17 2025 11:12:53 UTC)

// Verification Directory fv/counter 

module counter(count, rst, clk, m, SE, scan_in, scan_out);
  input rst, clk, m, SE, scan_in;
  output [3:0] count;
  output scan_out;
  wire rst, clk, m, SE, scan_in;
  wire [3:0] count;
  wire scan_out;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11;
  assign scan_out = count[3];
  OAI21X1 g159__2398(.A0 (n_8), .A1 (count[3]), .B0 (n_9), .Y (n_11));
  OAI21X1 g162__5107(.A0 (n_6), .A1 (count[2]), .B0 (n_7), .Y (n_10));
  NAND2XL g161__6260(.A (n_8), .B (count[3]), .Y (n_9));
  NAND2XL g163__4319(.A (n_6), .B (count[2]), .Y (n_7));
  OAI21XL g164__8428(.A0 (m), .A1 (n_3), .B0 (n_4), .Y (n_5));
  NAND2BX1 g165__5526(.AN (n_6), .B (n_0), .Y (n_8));
  NAND2XL g166__6783(.A (m), .B (n_3), .Y (n_4));
  OR2X1 g167__3680(.A (n_2), .B (n_3), .Y (n_6));
  MXI2XL g168__1617(.A (n_1), .B (count[0]), .S0 (m), .Y (n_2));
  MXI2XL g169__2802(.A (count[0]), .B (n_1), .S0 (count[2]), .Y (n_0));
  MXI2XL g170__1705(.A (n_1), .B (count[0]), .S0 (count[1]), .Y (n_3));
  CLKINVX1 g172(.A (count[0]), .Y (n_1));
  SDFFRHQX2 \count_reg[3] (.RN (rst), .CK (clk), .D (n_11), .SI
       (count[2]), .SE (SE), .Q (count[3]));
  SDFFRHQX2 \count_reg[2] (.RN (rst), .CK (clk), .D (n_10), .SI
       (count[1]), .SE (SE), .Q (count[2]));
  SDFFRHQX2 \count_reg[1] (.RN (rst), .CK (clk), .D (n_5), .SI
       (count[0]), .SE (SE), .Q (count[1]));
  SDFFRHQX2 \count_reg[0] (.RN (rst), .CK (clk), .D (n_1), .SI
       (scan_in), .SE (SE), .Q (count[0]));
endmodule

