
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Feb 17 2025 16:24:50 IST (Feb 17 2025 10:54:50 UTC)

// Verification Directory fv/counter 

module counter(count, rst, clk, m);
  input rst, clk, m;
  output [3:0] count;
  wire rst, clk, m;
  wire [3:0] count;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  OAI221X1 g160__2398(.A0 (count[2]), .A1 (n_3), .B0 (count[0]), .B1
       (n_6), .C0 (n_4), .Y (n_7));
  CLKINVX1 g161(.A (n_4), .Y (n_5));
  AOI221X1 g162__5107(.A0 (m), .A1 (n_3), .B0 (n_2), .B1 (count[0]),
       .C0 (n_1), .Y (n_4));
  MXI2XL g163__6260(.A (n_3), .B (count[0]), .S0 (count[1]), .Y (n_1));
  CLKINVX1 g165(.A (count[3]), .Y (n_0));
  INVXL g166(.A (m), .Y (n_2));
  CLKINVX1 g167(.A (count[2]), .Y (n_6));
  DFFRX2 \count_reg[0] (.RN (rst), .CK (clk), .D (n_3), .Q (count[0]),
       .QN (n_3));
  SDFFRHQX2 \count_reg[3] (.RN (rst), .CK (clk), .D (n_0), .SI
       (count[3]), .SE (n_7), .Q (count[3]));
  SDFFRHQX2 \count_reg[2] (.RN (rst), .CK (clk), .D (n_6), .SI
       (count[2]), .SE (n_5), .Q (count[2]));
  SDFFRHQX2 \count_reg[1] (.RN (rst), .CK (clk), .D (n_2), .SI (m), .SE
       (n_1), .Q (count[1]));
endmodule

